Version 3.0 of Machine queue. Simplified ticket system and everything can run over ssh

diff --git a/scripts/enqueue b/scripts/enqueue
--- a/scripts/enqueue
+++ b/scripts/enqueue
@@ -5,18 +5,32 @@ if [ "${SCRIPT_PATH}" == "" ]; then
     exit -1
 fi
 
-function EnqueueSynchronousUsage() {
+# List of a bunch of signals that we will try and trap on. This is basically a
+# 'if anything at all happens try and shut down our job cleanly' approach
+SIGNALS="SIGINT SIGTERM SIGHUP SIGQUIT SIGKILL SIGSTOP SIGPIPE"
+
+function SignalRemoveJob() {
+    local system=$1
+    local user=$2
+    # First do fast cleanup that doesn't require any locks
+    FastRemoveJob ${system} ${user}
+    echo "Received signal. Finishing clean up, please be patient"
+    # Now attempt to get the lock and do the rest of cleanup. But do so in a fast way
+    if FastLockSystem ${system}; then
+        RemoveJob ${system} ${user}
+        UnlockSystem ${system}
+    fi
+    exit -1
+}
+
+function EnqueueUsage() {
     echo "$0 run -r|-i|-c <string> -l logfile -s system -f file1 -f file2 .. -f filen"
     echo
     echo "   Enqueues a new job and then waits for it to complete before returning."
-    echo "   Jobs can include reservations and interactive sessions due to"
-    echo "   synchronous nature."
+    echo "   Jobs can include reservations due to synchronous nature."
     echo
     echo "   Output from the machine is generally collected and passed back to the"
     echo "   user both on stdout and in the form of an option logfile."
-    echo
-    echo "   stdin will be redirected to the machine in the case of interactive and"
-    echo "   reservation modes."
     echo
     echo "   Jobs can be canceled at any time with ^C, which will notify the server"
     echo "   if the job is running and remove the job from the queue."
@@ -26,7 +40,6 @@ function EnqueueSynchronousUsage() {
     echo "Options:"
     echo
     echo " -r          Reserves the device. Will not reboot or run an image"
-    echo " -i          Once the image is loaded and running stdin is connected for interactive use"
     echo " -c TEXT     Image is run until the specified regular completion text"
     echo " -l FILE     Optional location to write all the console output to"
     echo " -s TEXT     Specifies which machine this job is for"
@@ -34,7 +47,7 @@ function EnqueueSynchronousUsage() {
     echo
 }
 
-function EnqueueSynchronous() {
+function Enqueue() {
     # Parse the command line
     local file_count=0
     local logfile=""
@@ -43,6 +56,12 @@ function EnqueueSynchronous() {
     local files=""
     local system=""
     local file_prefix=""
+    local user=$USER
+    if [ "${user}" == "" ]; then
+        echo "Attempted to user USER environment variable to construct a user name"
+        echo "but received an empty string. Please set to your user name"
+        exit -1
+    fi
     while [ "$#" -ne 0 ]; do
         case "$1" in
             -l)
@@ -53,19 +72,10 @@ function EnqueueSynchronous() {
                 shift
                 completion="$1"
                 if [ "$interact" != "" ]; then
-                    EnqueueSynchronousUsage
+                    EnqueueUsage
                     exit -1
                 fi
                 interact="-c"
-            ;;
-            -i)
-                interact="-i"
-                echo "Interactive mode not currently supported. Please use -c and connect on consoles manually"
-                exit -1
-                if [ "$completion" != "" ]; then
-                    EnqueueSynchronousUsage
-                    exit -1
-                fi
             ;;
             -r)
                 interact="-r"
@@ -77,7 +87,7 @@ function EnqueueSynchronous() {
 #                    exit -1
 #                fi
                 if [ "$files" != "" ]; then
-                    files="$files\n"
+                    files="$files "
                 fi
                 files="$files$1"
                 (( file_count++ ))
@@ -95,7 +105,7 @@ function EnqueueSynchronous() {
             ;;
             *)
                 echo "Unknown option $1"
-                EnqueueSynchronousUsage
+                EnqueueUsage
                 exit -1
             ;;
         esac
@@ -104,11 +114,11 @@ function EnqueueSynchronous() {
 
     # Check that we got enough parameters
     if [ "$system" = "" ]; then
-        EnqueueSynchronousUsage
+        EnqueueUsage
         exit -1
     fi
     if [ "$interact" = "" ]; then
-        EnqueueSynchronousUsage
+        EnqueueUsage
         exit -1
     fi
 
@@ -127,46 +137,81 @@ function EnqueueSynchronous() {
         fi
     fi
 
-    # See what this user already has
-    local completed=$(CountJobs COMPLETE '.*' ${USER})
-    if [ ${completed} -ne 0 ]; then
-        echo "You already have ${completed} completed jobs that you have not cleaned up"
-        echo "Please collect these jobs"
+    echo "Acquring lock to enqueue for ${system}"
+
+    # Grab the main lock for the system
+    if ! LockSystem "${system}"; then
+        echo "Failed to acquire system (${system}) lock. Assuming kill occured, nothing to clean up"
         exit -1
     fi
 
-    # Grab the main lock
-    Lock
-    EnsureLock
+    echo "Seeing if ${user} already has a job for ${system}"
 
-    # Add the job
-    local jobid=$(AddJob "${system}" "${interact}")
-    if [ $? -ne 0 ] ; then
-        Unlock
-        # Error message in the job id
-        echo ${jobid}
+    # See if we have an outstanding lock or lock request for this system
+    if JobExists "${system}" "${user}"; then
+        echo "You already have a job queued or in progress for this system (${system})"
+        UnlockSystem "${system}"
         exit -1
     fi
 
-    echo "Created Job with ID ${jobid}"
-    echo "There are already $(( $(CountJobs QUEUED ${system} '.*') - 1 )) jobs in queue for ${system}"
-    if [ $(CountJobs RUNNING ${system} '.*') -ne 0 ] ; then
-        echo "Another job is already running on ${system}, you may have to wait"
-    fi
-
-    # Attempt to construct the job, will fail if anything went wrong
-    MakeJob ${jobid} "${file_prefix}" "${files}"
-    if [ $? -ne 0 ]; then
-        RemoveJob ${jobid}
-        Unlock
+    # Add a job. But first setup a signal handler that will try and remove a running job
+    echo "Attempting to add job for ${user} to ${system}"
+    trap "SignalRemoveJob ${system} ${user}" ${SIGNALS}
+    if ! AddJob "${system}" "${user}"; then
+        echo "Failed to add job somehow. Removing locks and exiting"
+        UnlockSystem "${system}"
         exit -1
     fi
 
     # Setup is done, release the lock
-    Unlock
+    UnlockSystem "${system}"
+    echo "Released queue lock for ${system}"
 
-    echo "Job is queued, notifying bamboo"
+    echo "Notifying bamboo to run ${system}"
     SystemNotifyBamboo ${system}
+
+    echo "Waiting for permission to run..."
+    # Now wait for the job
+    if ! WaitJob "${system}" "${user}"; then
+        # Assume ctrl+c, clean up ASAP. This does not require any locks
+        FastRemoveJob "${system}" "${user}"
+        # Now do the rest
+        if ! LockSystem "${system}"; then
+            echo "Failed to acquire system lock. Job may not have been cleaned up correctly"
+            exit -1
+        fi
+        RemoveJob "${system}" "${user}"
+        UnlockSystem "${system}"
+        echo "Failed to wait for the chance to run job. Cleaned up and now exiting"
+        exit -1
+    fi
+
+    echo "We are allowed to run"
+    local ret=0
+
+    if [ "${interact}" = "-r" ]; then
+        echo "This is a reservation. You now own ${system} and"
+        echo "can do what you want. Press ctrl+d or enter here when done"
+        read line
+    else
+        # Run the image. 'files' is deliberately no in quotes so the multiple
+        # files expands to multiple arguments
+        SystemRunImage ${system} "${completion}" "${logfile}" $files
+        ret=$?
+    fi
+
+
+    echo "All done. Cleaning up job for ${user} on ${system}"
+    if ! LockSystem ${system}; then
+        FastRemoveJob ${system} ${user}
+        echo "Failed to acquire lock to cleanup job. Cleaning up what we can without a lock"
+        exit -1
+    fi
+
+    RemoveJob ${system} ${user}
+    UnlockSystem ${system}
+
+    exit $ret
 
     # Setup the output pipe that will feed data from the console
     # to the user terminal
diff --git a/scripts/job b/scripts/job
--- a/scripts/job
+++ b/scripts/job
@@ -9,201 +9,96 @@ fi
 # 'if anything at all happens try and shut down our job cleanly' approach
 SIGNALS="SIGINT SIGTERM SIGHUP SIGQUIT SIGKILL SIGSTOP SIGPIPE"
 
-function NewJobID() {
-    # Increment job ID
-    EnsureLock
-    local last_jobid=`ReadQueue | cut -f 1 -d' ' | sort -n | tail -1`
-    local jobid="0"
-    if [ "$last_jobid" != "" ]; then
-        (( jobid = last_jobid + 1 ))
-    fi
-    echo "${jobid}"
+function JobWantLock() {
+    local system=$1
+    local user=$2
+    echo "${BASE}/${system}/job_want_${user}.lock"
 }
 
-function CountJobs() {
-    local jobtype="$1"
-    local system="$2"
-    local user="$3"
-    ReadQueue | cut -d' ' -f 2,3,4 | grep "${jobtype} ${system} ${user}" | wc -l | cut -f 1 -d' '
+function JobCompleteLock() {
+    local system=$1
+    local user=$2
+    echo "${BASE}/${system}/job_complete_${user}.lock"
+}
+
+# Makes a lock assuming that it doesn't exist
+function MakeLock() {
+    local lock=$1
+    RemoteCommand lockfile -1 -r 1 "${lock}"
+    if [ $? -eq 0 ]; then
+        RemoteCommand chown -f :ertos_src "${lock}" 2>&1 > /dev/null
+        return 0
+    fi
+    return -1
+}
+
+function RemoveLock() {
+    local lock=$1
+    RemoteCommand rm -f "${lock}"
 }
 
 function RemoveJob() {
-    local jobid=$1
-    local jobdir=$(JobDir ${jobid})
-    rm -rf "${jobdir}"
-    RemoveFromQueue "${jobid}"
+    local system=$1
+    local user=$2
+    # Remove the two locks
+    RemoveLock "$(JobWantLock ${system} ${user})"
+    RemoveLock "$(JobCompleteLock ${system} ${user})"
+    # Now remove from the queue
+    RemoveFromQueue ${system} ${user}
 }
 
 function AddJob() {
     local system=$1
-    local interact=$2
-    local date=$(date +"%D %T")
-    local jobid=$(NewJobID)
-    local user=$USER
-    local jobline="${jobid} QUEUED ${system} ${user} ${date} ${interact}"
-    # Verify there aren't extra spaces/lines in our jobline that will confuse us later
-    # Note that the date has two parts
-    if [ $(echo ${jobline} | wc -l) -ne 1 ] || [ $(echo ${jobline} | wc -w) -ne 7 ] ; then
-        echo "Space or newline found unexpectedly in parameters"
-        return 1
-    fi
-    # Add the line to the queue
-    AddToQueue "${jobline}"
-    echo ${jobid}
-    return 0
-}
-
-function JobDir() {
-    local jobid=$1
-    echo "${BASE}/${jobid}"
-}
-
-function InPipe() {
-    local jobid=$1
-    echo "$(JobDir ${jobid})/input.pipe"
-}
-
-function OutPipe() {
-    local jobid=$1
-    echo "$(JobDir ${jobid})/output.pipe"
-}
-
-function JobLock() {
-    local jobid=$1
-    echo "$(JobDir ${jobid})/complete.lock"
-}
-
-function JobOutput() {
-    local jobid=$1
-    echo "$(JobDir ${jobid})/output"
-}
-
-function JobError() {
-    local jobid=$1
-    local error_path="$(JobDir ${jobid})/return"
-    if [ -e "${error_path}" ]; then
-        cat "${error_path}"
-    else
-        echo "0"
-    fi
-}
-
-function MakeJob() {
-    # Make the directory for the job
-    local jobid=$1
-    local jobdir=$(JobDir ${jobid})
-    local file_prefix=$2
-    local files=$3
-    mkdir "$jobdir"
+    local user=$2
+    # Remove any existing lockfiles
+    RemoveLock "$(JobWantLock ${system} ${user})"
+    RemoveLock "$(JobCompleteLock ${system} ${user})"
+    # Create the two lockfiles
+    MakeLock "$(JobWantLock ${system} ${user})"
     if [ $? -ne 0 ]; then
-        echo "Failed to make job directory"
-        return 1
+        return -1
     fi
-    # Copy all the files, unless the job is just a reservation
-    if [ "$interact" != "-r" ]; then
-        i=0
-        echo -e "$files" | while read file; do
-            echo "Copying input file ($i) \"$file\""
-            scp "${file_prefix}$file" "$jobdir/file$i"
-            if [ $? -ne 0 ]; then
-                echo "Error copying file"
-                return 1
-            fi
-            i=`expr "$i" + 1`
-        done
-        if [ "$interact" = "-c" ]; then
-            echo -e "$completion" > "$jobdir/completion"
-        fi
-    fi
-
-    # Construct the output pipe
-    mkfifo "$(OutPipe ${jobid})"
+    MakeLock "$(JobCompleteLock ${system} ${user})"
     if [ $? -ne 0 ]; then
-        echo "Error making output pipe"
-        return 1
+        RemoveLock "$(JobWantLock ${system} ${user})"
+        return -1
     fi
-
-    mkfifo "$(InPipe ${jobid})"
-    if [ $? -ne 0 ]; then
-        echo "Error making input pipe"
-        return 1
-    fi
-
-    # Create the completion semaphore
-    lockfile "$(JobLock ${jobid})"
-    if [ $? -ne 0 ]; then
-        echo "Error creating lockfile"
-        return 1
-    fi
-
-    # Make sure permissions are sane
-    chown :ertos_src -R "$jobdir"
-    chmod g+rw -R "$jobdir"
-    chmod g+x "$jobdir"
+    AddToQueue ${system} ${user}
 }
 
-function JobExists() {
-    local jobid=$1
-    ReadQueue | grep -q "^${jobid}"
+function WaitJobComplete() {
+    local system=$1
+    local user=$2
+    # Wait until the lockfile appears
+    LockFileInteractive "$(JobCompleteLock ${system} ${user})"
+}
+
+function WaitJob() {
+    local system=$1
+    local user=$2
+    # Wait until the lockfile appears
+    LockFileInteractive "$(JobWantLock ${system} ${user})"
+}
+
+function LockExists() {
+    local lock=$1
+    RemoteCommand [ -e "${lock}" ]
     return $?
 }
 
-function JobStatus() {
-    local jobid=$1
-    if ! JobExists "${jobid}"; then
-        echo "Cannot query status of nonexistent job!"
-    fi
-    ReadQueue | grep "^${jobid}" | cut -d' ' -f 2
+function JobExists() {
+    local system=$1
+    local user=$2
+#    ReadQueue ${system} | grep -q "^${user}\$" || LockExists "$(JobWantLock ${system} ${user})" || LockExists "$(JobCompleteLock ${system} ${user})"
+    ReadQueue ${system} | grep -q "^${user}\$"
+    return $?
 }
 
-# If the job we enqued is still queued (and not running or completed) then removeit it
-# sets a return value for whether the job was running or not
-function RemoveIfQueued() {
-    local jobid=$1
-    local result
-    Lock
-    if [ $(JobStatus ${jobid}) == QUEUED ]; then
-        RemoveJob ${jobid}
-        result=1
-    else
-        result=0
-    fi
-    Unlock
-    return $result
-}
-
-function CleanupJob() {
-    local jobid=$1
-    # pid of the process echoing the output pipe
-    local outpid=$2
-    local closeremote=$3
-    local interact=$4
-    RemoveIfQueued ${jobid}
-    result=$?
-    if [ ${result} -ne 0 ]; then
-        signal_did_cleanup=1;
-    fi
-    if [ "$closeremote" -ne 0 ]; then
-        # We need to notify the server. But only if we were running
-        # If we weren't running then the server will not be listening
-        # so we are done
-        # If we were running then don't exit yet so we can try
-        # and keep running and get any partial output
-        # Reset the signal handler to not close the remote incase someone
-        # is spammy with the signals
-        trap 'CleanupJob ${jobid} ${outpid} 0' $SIGNALS
-        if [ ${result} -ne 0 ]; then
-            # Pack up and go home
-            kill -- -$outpid
-        else
-            echo "Cleaning up job, please wait a few seconds"
-            # If we are waiting till completion text then we need to explicitly tell the
-            # remote server that we are finished
-            if [ "${interact}" = "-c" ]; then
-                echo "Close" > $(InPipe ${jobid})
-            fi
-        fi
-    else
-        kill -- -$outpid
-    fi
+# This function operates WITHOUT holding the lock
+# Attempts to clean up the bare minimum of a job such that
+# it will not block other jobs from running
+function FastRemoveJob() {
+    local system=$1
+    local user=$2
+    RemoveLock "$(JobCompleteLock ${system} ${user})"
 }
diff --git a/scripts/lock b/scripts/lock
--- a/scripts/lock
+++ b/scripts/lock
@@ -5,38 +5,37 @@ if [ "${SCRIPT_PATH}" == "" ]; then
     exit -1
 fi
 
-LOCKTIMEOUT=60
-RUNQUEUELOCK="${BASE}/runqueue.lock"
+function LockName() {
+    local system=$1
+    echo "${BASE}/${system}/queue.lock"
+}
 
-# Remember in shell land that true and false are inverted, with 0 being true
-have_queue_lock=1
+function LockSystem() {
+    local system=$1
+    # Retry the lock every second, retrying 60 times for a total of 1 minute
+    # If we don't get it after that then the lock is bugged
+    RemoteCommand lockfile -1 -r 60 "$(LockName ${system})"
+    return $?
+}
 
-function HaveLock() {
-    return $have_queue_lock
+function FastLockSystem() {
+    local system=$1
+    # Retry the lock every second for 2 seconds
+    RemoteCommand lockfile -1 -r 2 "$(LockName ${system})"
+    return $?
 }
-function Lock() {
-    if HaveLock; then
-        echo "Already have lock! Scripts are fucked"
-        exit -1
-    fi
-    lockfile -l "$LOCKTIMEOUT" "$RUNQUEUELOCK"
-    if [ $? -eq 0 ]; then
-        have_queue_lock=0
-    fi
+
+# Performs lockfile, but does scaling delay to acquire the lock fast
+# under the assumption that it should be free. Then slows down to conserve resources
+function LockFileInteractive() {
+    local lock=$1
+    # Try every 2 seconds
+    RemoteCommand lockfile -2 "${lock}"
+    return $?
 }
-function Unlock() {
-    if ! HaveLock; then
-        echo "Do not have lock! Why are we releasing it? Scripts are fucked"
-        exit -1
-    else
-        rm -f "$RUNQUEUELOCK"
-    fi
-    have_queue_lock=1
-}
-function EnsureLock() {
-    if ! HaveLock; then
-        echo "Cannot create job without lock!"
-        exit -1
-    fi
+
+function UnlockSystem() {
+    local sytem=$1
+    RemoteCommand rm -f "$(LockName ${system})"
 }
 
