Add flag for running mq without modifying locks (although you must already own a lock to be successful)

diff --git a/scripts/enqueue b/scripts/enqueue
--- a/scripts/enqueue
+++ b/scripts/enqueue
@@ -26,6 +26,7 @@ function EnqueueUsage() {
     echo "Options:"
     echo
     echo " -r          Reserves the device. Will not reboot or run an image"
+    echo " -n          No lock changes. Checks that you have the lock, and then runs an image. Will not unlock afterwards."
     echo " -c TEXT     Image is run until the specified regular completion text"
     echo " -d TIME     Timeout (in seconds) to wait for the completion text (default -1 AKA no timeout)"
     echo " -l FILE     Optional location to write all the console output to"
@@ -43,6 +44,7 @@ function Enqueue() {
     local total_retries=-1
     local logfile=""
     local interact=""
+    local no_lock_mods=false
     local completion=""
     local completion_timeout=-1
     local files=""
@@ -69,6 +71,9 @@ function Enqueue() {
             ;;
             -r)
                 interact="-r"
+            ;;
+            -n)
+                no_lock_mods=true
             ;;
             -f)
                 shift
@@ -136,19 +141,27 @@ function Enqueue() {
         fi
     fi
 
-    echo "Acquiring lock for ${system}"
+    if ${no_lock_mods} ; then
+        if ! LockIOwn "${system}"; then
+            echo "Failed to run because you said you own the lock (-n flag), but you don't!"
+            LockSystemPrintInfo "${system}"
+            exit -1
+        fi
+    else
+        echo "Acquiring lock for ${system}"
 
-    # Print out potentially useful information to the user about
-    # the current status of the lock
-    LockSystemPrintInfo "${system}"
+        # Print out potentially useful information to the user about
+        # the current status of the lock
+        LockSystemPrintInfo "${system}"
 
-    # We can setup the trap early as we check if we actually own the
-    # the lock before releasing it
-    trap "UnlockSystem ${system} 0; exit 1" ${SIGNALS}
+        # We can setup the trap early as we check if we actually own the
+        # the lock before releasing it
+        trap "UnlockSystem ${system} 0; exit 1" ${SIGNALS}
 
-    if ! LockSystem "${system}" "${retry_period}" "${total_retries}"; then
-        echo "Failed to acquire lock for system (${system})"
-        exit 2
+        if ! LockSystem "${system}" "${retry_period}" "${total_retries}"; then
+            echo "Failed to acquire lock for system (${system})"
+            exit 2
+        fi
     fi
 
     echo "Lock acquire, we are allowed to run"
@@ -167,9 +180,10 @@ function Enqueue() {
         ret=$?
     fi
 
-
-    UnlockSystem ${system} 0
-    trap "exit 1" ${SIGNALS}
+    if ! ${no_lock_mods} ; then
+        UnlockSystem ${system} 0
+        trap "exit 1" ${SIGNALS}
+    fi
 
     exit $ret
 
