Add Cheshire (+bitstream FPGA image support) to MQ
Signed-off-by: julia <git.ts@trainwit.ch>

diff --git a/scripts/runner b/scripts/runner
--- a/scripts/runner
+++ b/scripts/runner
@@ -77,8 +77,17 @@ RebootConsoleRunTwoFiles() {
                 return 1
             fi
         fi
+        if [ ! -z "${bitstream}" ]; then
+            bitstreamfile=$(RemoteCommandOn ${HOST} "mktemp")
+            bitstreamflag="--bitstream $bitstreamfile"
+            if ! scp "${bitstream}" "${HOST}:${bitstreamfile}"; then
+                echo "Failed to copy bitstream file"
+                RemoteCommandOn ${HOST} rm -f "${kernelfile}" "${rootserverfile}" "${logfile}" "${dtbfile}" "${bitstreamfile}"
+                return 1
+            fi
+        fi
 
-        ssh -tt -oLogLevel=quiet ${HOST} "stty isig -echoctl -echo; /tftpboot/${machine}/reboot $linux $dtbflag -l '${logfile}' -c '${completion}' -t '${completion_timeout}' -e '${errortxt}' -k '${kernelfile}' -u '${rootserverfile}' ${ka_flag}"
+        ssh -tt -oLogLevel=quiet ${HOST} "stty isig -echoctl -echo; /tftpboot/${machine}/reboot $linux $dtbflag $bitstreamflag -l '${logfile}' -c '${completion}' -t '${completion_timeout}' -e '${errortxt}' -k '${kernelfile}' -u '${rootserverfile}' ${ka_flag}"
         ret=$?
         if [ "${output}" != "" ]; then
             scp "${HOST}:${logfile}" "${output}"
@@ -87,12 +96,15 @@ RebootConsoleRunTwoFiles() {
         if [ ! -z "${dtb}" ]; then
             RemoteCommandOn ${HOST} rm -f "${dtbfile}"
         fi
+        if [ ! -z "${bitstream}" ]; then
+            RemoteCommandOn ${HOST} rm -f "${bitstreamfile}"
+        fi
         return $ret
     fi
     if [ "${output}" = "" ]; then
-        "/tftpboot/${machine}/reboot"  $linux $dtbflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -k "${kernel}" -u "${rootserver}" ${ka_flag}
+        "/tftpboot/${machine}/reboot"  $linux $dtbflag $bitstreamflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -k "${kernel}" -u "${rootserver}" ${ka_flag}
     else
-        "/tftpboot/${machine}/reboot" $linux $dtbflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -l "${output}" -k "${kernel}" -u "${rootserver}" ${ka_flag}
+        "/tftpboot/${machine}/reboot" $linux $dtbflag $bitstreamflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -l "${output}" -k "${kernel}" -u "${rootserver}" ${ka_flag}
     fi
 }
 
@@ -104,6 +116,11 @@ RebootConsoleRunOneFile() {
     [ "$1" = '-b' ] && {
     shift
     dtb="$1"
+    shift
+    }
+    [ "$1" = '--bitstream' ] && {
+    shift
+    bitstream="$1"
     shift
     }
     completion=$1
@@ -134,13 +151,21 @@ RebootConsoleRunOneFile() {
         if [ ! -z "${dtb}" ]; then
             dtbfile=$(RemoteCommandOn ${HOST} "mktemp")
             dtbflag="-b $dtbfile"
-            if ! scp "${dtb}" "${HOST}:${kernelfile}"; then
+            if ! scp "${dtb}" "${HOST}:${dtbfile}"; then
                 echo "Failed to copy dtb file"
                 RemoteCommandOn ${HOST} rm -f "${dtbfile}" "${kernelfile}" "${logfile}"
             fi
         fi
+        if [ ! -z "${bitstream}" ]; then
+            bitstreamfile=$(RemoteCommandOn ${HOST} "mktemp")
+            bitstreamflag="--bitstream $bitstreamfile"
+            if ! scp "${bitstream}" "${HOST}:${bitstreamfile}"; then
+                echo "Failed to copy bitstream file"
+                RemoteCommandOn ${HOST} rm -f "${bitstreamfile} ${dtbfile}" "${kernelfile}" "${logfile}"
+            fi
+        fi
 
-        ssh -tt -oLogLevel=quiet ${HOST} "stty isig -echoctl -echo; /tftpboot/${machine}/reboot $linux $dtbflag -l '${logfile}' -c '${completion}' -t '${completion_timeout}' -e '${errortxt}' -k '${kernelfile}' ${ka_flag}"
+        ssh -tt -oLogLevel=quiet ${HOST} "stty isig -echoctl -echo; /tftpboot/${machine}/reboot $linux $dtbflag $bitstreamflag -l '${logfile}' -c '${completion}' -t '${completion_timeout}' -e '${errortxt}' -k '${kernelfile}' ${ka_flag}"
         ret=$?
         if [ "${output}" != "" ]; then
             scp "${HOST}:${logfile}" "${output}"
@@ -149,11 +174,14 @@ RebootConsoleRunOneFile() {
         if [ ! -z "${dtb}" ]; then
             RemoteCommandOn ${HOST} rm -f "${dtbfile}"
         fi
+        if [ ! -z "${bitstream}" ]; then
+            RemoteCommandOn ${HOST} rm -f "${bitstreamfile}"
+        fi
         return $ret
     fi
     if [ "${output}" = "" ]; then
-        "/tftpboot/${machine}/reboot" $linux $dtbflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -k "${kernel}" ${ka_flag}
+        "/tftpboot/${machine}/reboot" $linux $dtbflag $bitstreamflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -k "${kernel}" ${ka_flag}
     else
-        "/tftpboot/${machine}/reboot" $linux $dtbflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -l "${output}" -k "${kernel}" ${ka_flag}
+        "/tftpboot/${machine}/reboot" $linux $dtbflag $bitstreamflag -t "${completion_timeout}" -c "${completion}" -e "${errortxt}" -l "${output}" -k "${kernel}" ${ka_flag}
     fi
 }
